bundle.go, cmd/root.go, dispatch.go, js/00_opcodes.js, logger.go, main.go, report.go
=> feat: fs perms

.github/workflows/build.yml, bundle.go, cache.go, dispatch.go, go.mod, go.sum, main.go
- Small formatting issues (go-vet)
- Change imports from "divy-work" to "elsaland"
=> Prepare project for contribution

cmd/root.go, go.mod, go.sum, packager/exec.go, packager/packager.go, packager/template.go
=> feat!: implement elsa packager

COMPARISON.md
=> docs(md): add elsa / deno / node comparison table

COMPARISON.md
=> Minor fix in COMPARISON.md

core/run.go, testing/pending_jobs.js
=> feat: implement pending job resolution

Makefile, bundle.go, go.sum, testing/url_imports.ts
=> refractor: url bundler

core/dispatch.go, core/ops/fetch.go, go.mod, go.sum, js/00_core.js, js/03_fetch.js, testing/fetch.js
Basic fetch implementation (not yet according to web standards)
=> feat: add fetch API

core/dispatch.go, core/ops.go, core/ops/fs.go, go.sum, js/00_core.js, js/01_namespace.js
Hi, I think I have the mkdir implementation ready, I will send the pr as a draft for you to review since it i'm had problems with the compilation and `gcc`
=> feat: mkdir function support

core/console.go, core/logger.go, go.mod, go.sum
=> Use color.Output for Windows.

std/fs/exist.ts
this is a starting point to start the standard library for elsa
=> feat(draft): standard library

testing/bundle/basics.js.mini.out, testing/bundle_test.go
Since the bundler now has a `minify` parameter, I think it would be appropriate to have a test for it
=> test(bundle): add test for minify option

std/async/README.md, std/async/deffered.ts, std/async/delay.ts, std/async/mux_async_iterator.ts, std/async/pool.ts, std/bytes/README.md, std/bytes/bytes.ts, std/uuid/common.ts, std/uuid/v1.ts, std/uuid/v4.ts, std/uuid/v5.ts
Huge thanks to the Deno team :smile:
=> feat: implement deno compatible std modules.

bundler/bundle.go
Fixes issue: https://github.com/elsaland/elsa/issues/32
=> #32 bundle respects custom tsconfig

bundler/bundle.go, core/dispatch.go, core/ops.go, core/ops/fetch.go, core/ops/serve.go, core/options/options.go, js/00_core.js, js/01_namespace.js, js/02_console.js, js/03_fetch.js, js/04_event.js, js/05_compiler.js, js/06_encoder.js, js/10_window.js, std/encoding/hex.ts, std/fmt/colors.ts, std/hash/aes.ts, std/hash/hasher.ts, std/hash/md5.ts, std/hash/sha1.ts, std/hash/sha256.ts, std/hash/sha512.ts, testing/http/serve.js, testing/web/encode.js
=> feat(std/hash): hash lib

core/ops/serve.go
The sync.WaitGroup (which was ineffectual, see #77) has been replaced with an error channel in preparation for #75 so that http.ListenAndServe's error can eventually be thrown at the script that called Elsa.serve.
Renamed some variables to be more clear, also removed redundant comments.
Made the requests and responses channels unbuffered.
Let me know if there are any changes I should make.
=> make improvents to ops.Serve

Makefile, cmd/root.go, dev/dev.go, dev/report.go, dev/typescript.go, js/05_compiler.js, testing/typescript/import.ts, testing/typescript/typeerror.ts
Closes #67 
Adds support for URL imports, ~~updates Elsa namespace typings~~, logic for resolving relative imports
EDIT: typings for the namespace will be added after #76 is fixed
=> feat(dev/compile): improve typechecking 

js/07_testing.js, std/fmt/colors.ts, std/hash/sha1.ts, testing/tests/tests.js
The test runner fulfills basic requirement for unit testing. Utilities like `assert`, etc should be a part of the std.
USAGE:
```js
Elsa.tests({
"adds numbers": function () {
eq(6, add(2, 4));
eq(6.6, add(2.6, 4));
},
"subtracts numbers": function () {
eq(-2, add(2, -4));
},
"add fail": function () {
eq(2, add(2, 1));
},
});
```
=> feat(js/testing): add Elsa.tests - tiny test runner

core/dispatch.go, core/ops.go, core/ops/fs.go, js/00_core.js, js/01_namespace.js, js/05_compiler.js, testing/fs/stats.js
=> fix(ops/fs): rename Elsa.stats => Elsa.stat

bundler/bundle.go, cmd/root.go, testing/tests/test1_test.js, testing/tests/test_test.js, testing/tests/utils.ts
=> feat(cmd/test): add elsa test like deno test

cmd/root.go, core/options/options.go, core/run.go, dev/typescript.go, js/07_testing.js, testing/miscellaneous/mode.js, testing/tests/mode_test.js, testing/tests/utils.ts
=> feat(core/testing): finalise Elsa.tests

dev/dev.go, dev/report.go, js/05_compiler.js
=> feat: pretty print typescript diagnostics

.gitignore, std/fmt/colors.ts
=> feat(std/fmt): colors #69

.github/workflows/build.yml
This pull request includes a fix for Windows build, and add a better seperation between Mac, Linux & Windows.
=> [improvement/fix] Improved CI & make Windows build working

cmd/root.go, go.mod, go.sum
=> feat(cmd/install): add elsa install subcommand logic

cmd/root.go
now add to windows installed scripts `.cmd` so they can be run in powershell and cmd
=> fix(cmd/root): add .cmd in windows in elsa install script

core/dispatch.go, core/ops.go, core/ops/fs.go, js/00_core.js, js/01_namespace.js
example:
```ts
for (const { Path, Name } of Elsa.walk("./files")) {
}
```
=> feat(core/ops): add walk files support

COMPARISON.md
Source: https://deno.land/manual/tools/compiler
=> Yes for compiling to executable on Deno JS.
